// web socket service (this will be autogenerated)
define([""],
function(){
	function UserWebSocketService(){
		 this.requests = new Object();
	};

	UserWebSocketService.prototype.doGetUserRequest = function(request){
		var requestId = randomUUID();
		request.setRequestId(requestId);
		this.requests[requestId] = request; 
	};
	 
	UserWebSocketService.prototype.onGetUserResponse = function(response){
	    var request = this.requests[response.getRequestId()];
	    delete this.requests[response.getRequestId()];
	    var event = new CustomEvent("onGetUserRequestResponse", {"detail":{"request":request, "response":response}});
		window.dispatchEvent(event);
	};
	var userWebSocketService = new UserWebSocketService();
	window.addEventListener("onGetUserResponse", function(e){userWebSocketService.onGetUserResponse(e.detail);}, false);
	
	return userWebSocketService;
});
